mutation CreateAnaMessage($text: String!, $imageBase64: String!) @auth(level: PUBLIC) {
  anaMessage_insert(
    data: { text: $text, imageBase64: $imageBase64 }
  ) {
    id
    text
    imageBase64
    createdAt
    updatedAt
  }
}
